export const supportedProtocols = {
  1: {
    "Aave V1": "aave-v1",
    "Aave V2": "aave-v2",
    Ambient: "ambient",
    "Angle Savings": "angle-savings",
    "Angle Transmuter": "angle-transmuter",
    ApeSwap: "apeswap",
    "Balancer V1": "balancer-v1",
    "Balancer V2 Stable": "balancer-v2-stable",
    "Balancer V2 Weighted": "balancer-v2-weighted",
    BambooDeFi: "bamboodefi",
    "Bancor V2": "bancor-v2",
    "Bancor V3": "bancor-v3",
    "Beefy Finance": "beefy-finance",
    "Blueprint V3": "blueprint-v3",
    "Button Wrappers": "button-wrappers",
    "Capital DEX": "capital-dex",
    Carbon: "carbon",
    ChickenSwap: "chickenswap",
    Clober: "clober",
    "Compound V2": "compound-v2",
    Convergence: "convergence",
    "Convex CRV Depositor": "convex-crv-depositor",
    "Convex FXS Depositor": "convex-fxs-depositor",
    "Curve Crypto Factory": "curve-crypto-factory",
    "Curve Crypto Registry": "curve-crypto-registry",
    "Curve Factory": "curve-factory",
    "Curve LLAMMA": "curve-llamma",
    "Curve Registry": "curve-registry",
    "Curve Stable NG": "curve-stable-ng",
    "Curve TriCrypto NG": "curve-tricrypto-ng",
    "Curve TwoCrypto NG": "curve-twocrypto-ng",
    "DAI PSM (GUSD)": "dai-psm-gusd",
    "DAI PSM (USDC)": "dai-psm-usdc",
    "DAI PSM (USDP)": "dai-psm-usdp",
    "Defi Swap": "defi-swap",
    "Dodo V1": "dodo-v1",
    "Dodo V2": "dodo-v2",
    "Elk Finance": "elk-finance",
    "Empire DEX": "empire-dex",
    "Equalizer Finance": "equalizer-finance",
    Fraxswap: "fraxswap",
    "Fraxswap V2": "fraxswap-v2",
    Hashflow: "hashflow",
    Integral: "integral",
    "Iron Bank": "iron-bank",
    KwikSwap: "kwikswap",
    "Kyber DMM": "kyber-dmm",
    "Kyberswap Elastic": "kyberswap-elastic",
    "Lido stETH": "lido-steth",
    "Lido wstETH": "lido-wsteth",
    "Lif3 V3": "lif3-v3",
    LuaSwap: "luaswap",
    Maverick: "maverick",
    mStable: "mstable",
    Native: "native",
    NEOPIN: "neopin",
    "Olympus Staking": "olympus-staking",
    "Orion Protocol": "orion-protocol",
    PancakeSwap: "pancakeswap",
    "PancakeSwap V3": "pancakeswap-v3",
    "POL Migrator": "pol-migrator",
    Poolside: "poolside",
    RadioShack: "radioshack",
    "Saddle Finance": "saddle-finance",
    "SafeMoon Swap": "safemoon-swap",
    SafeSwap: "safeswap",
    SaitaSwap: "saitaswap",
    SakeSwap: "sakeswap",
    "Savings DAI": "savings-dai",
    sfrxETH: "sfrxeth",
    ShibaSwap: "shibaswap",
    SmarDex: "smardex",
    SnowSwap: "snowswap",
    "Solidly V2 Stable": "solidly-v2-stable",
    "Solidly V2 Volatile": "solidly-v2-volatile",
    "Solidly V3": "solidly-v3",
    "Standard Protocol": "standard-protocol",
    Stepn: "stepn",
    stFLIP: "stflip",
    SumSwap: "sumsum",
    SunflowerSwap: "sunflowerswap",
    "Sushi Bar": "sushibar",
    SushiSwap: "sushiswap",
    "SushiSwap V3": "sushiswap-v3",
    "Swaap V2": "swaap-v2",
    Swapr: "swapr",
    Swerve: "swerve",
    SwipeSwap: "swipeswap",
    Synapse: "synapse",
    "Synthetix Atomic": "synthetix-atomic",
    "Synthetix Wrapper DAI": "synthetix-wrapper-dai",
    "Synthetix Wrapper LUSD": "synthetix-wrapper-lusd",
    "Synthetix Wrapper WETH": "synthetix-wrapper-weth",
    "Temple DAO": "temple-dao",
    Tenderizer: "tenderizer",
    TenderSwap: "tenderswap",
    "Trader Joe V2.1": "traderjoe-v2.1",
    "Uniswap V1": "uniswap-v1",
    "Uniswap V2": "uniswap-v2",
    "Uniswap V3": "uniswap-v3",
    Verse: "verse",
    Wombat: "wombat",
    Woofy: "woofy",
    "Wrapped Ether": "wrapped-ether",
    "Wrapped USDM": "wrapped-usdm",
    xSigma: "xsigma",
    YapeSwap: "yapeswap",
    "Yearn iEarn": "yearn-iearn",
    "Yearn V1": "yearn-v1",
    "Yearn V2": "yearn-v2",
    YouSwap: "youswap",
    ZeusSwap: "zeusswap",
  },
  10: {
    "Aave V3": "aave-v3",
    "Angle Savings": "angle-savings",
    "Beefy Finance": "beefy-finance",
    "Beethoven X Stable": "beethoven-x-stable",
    "Beethoven X Weighted": "beethoven-x-weighted",
    "Curve Factory": "curve-factory",
    "Curve Registry": "curve-registry",
    "Curve Stable NG": "curve-stable-ng",
    "Curve TriCrypto NG": "curve-tricrypto-ng",
    "Curve TwoCrypto NG": "curve-twocrypto-ng",
    "DackieSwap V2": "dackieswap-v2",
    "DackieSwap V3": "dackieswap-v3",
    "Elk Finance": "elk-finance",
    Fraxswap: "fraxswap",
    "Fraxswap V2": "fraxswap-v2",
    Hashflow: "hashflow",
    "Iron Bank": "iron-bank",
    "Kyber DMM": "kyber-dmm",
    "Kyberswap Elastic": "kyberswap-elastic",
    "Lighter V2": "lighter-v2",
    Minerva: "minerva",
    "Mummy Finance": "mummy-finance",
    "OPX Finance": "opx-finance",
    "Overnight Exchange": "overnight-exchange",
    "Overnight Wrapper": "overnight-wrapper",
    PoolTogether: "pooltogether",
    RadioShack: "radioshack",
    "Rubicon V2": "rubicon-v2",
    "Saddle Finance": "saddle-finance",
    "Solidly V3": "solidly-v3",
    "Sonne Finance": "sonne-finance",
    "SushiSwap V3": "sushiswap-v3",
    Synapse: "synapse",
    "Synthetix Atomic": "synthetix-atomic",
    "Synthetix Wrapper DAI": "synthetix-wrapper-dai",
    "Synthetix Wrapper LUSD": "synthetix-wrapper-lusd",
    "Synthetix Wrapper WETH": "synthetix-wrapper-weth",
    "Uniswap V2": "uniswap-v2",
    "Uniswap V3": "uniswap-v3",
    "Velodrome Slipstream": "velodrome-slipstream",
    "Velodrome Stable": "velodrome-stable",
    "Velodrome Volatile": "velodrome-volatile",
    "Velodrome V2 Converter": "velodrome-v2-converter",
    "Velodrome V2 Stable": "velodrome-v2-stable",
    "Velodrome V2 Volatile": "velodrome-v2-volatile",
    Wombat: "wombat",
    "WOOFi V2": "woofi-v2",
    "Wrapped Ether": "wrapped-ether",
    ZipSwap: "zipswap",
    "ZyberSwap V3": "zyberswap-v3",
  },
  137: {
    "Aave V2": "aave-v2",
    "Aave V3": "aave-v3",
    "ACY Finance": "acy-finance",
    "Angle Savings": "angle-savings",
    ApeSwap: "apeswap",
    AuraSwap: "auraswap",
    "Balancer V2 Stable": "balancer-v2-stable",
    "Balancer V2 Weighted": "balancer-v2-weighted",
    BambooDeFi: "bamboodefi",
    "Beefy Finance": "beefy-finance",
    CafeSwap: "cafeswap",
    Clober: "clober",
    ComethSwap: "comethswap",
    "Cryption PolyDEX": "cryption-polydex",
    "Curve Crypto Factory": "curve-crypto-factory",
    "Curve Crypto Registry": "curve-crypto-registry",
    "Curve Factory": "curve-factory",
    "Curve Registry": "curve-registry",
    "Curve Stable NG": "curve-stable-ng",
    "Curve TriCrypto NG": "curve-tricrypto-ng",
    "Curve TwoCrypto NG": "curve-twocrypto-ng",
    Dfyn: "dfyn",
    DinoSwap: "dinoswap",
    "Dodo V1": "dodo-v1",
    "Dodo V2": "dodo-v2",
    "Dystopia Stable": "dystopia-stable",
    "Dystopia Volatile": "dystopia-volatile",
    "Elk Finance": "elk-finance",
    "Empire DEX": "empire-dex",
    FATExFI: "fatexfi",
    Firebird: "firebird",
    "Firebird Oneswap": "firebird-oneswap",
    Fraxswap: "fraxswap",
    "Fraxswap V2": "fraxswap-v2",
    "Gravis Finance": "gravis-finance",
    Greenhouse: "greenhouse",
    Hashflow: "hashflow",
    HoneySwap: "honeyswap",
    IronSwap: "ironswap",
    JamonSwap: "jamonswap",
    JavaSwap: "javaswap",
    JetSwap: "jetswap",
    "Just Money": "just-money",
    KwikSwap: "kwikswap",
    "Kyber DMM": "kyber-dmm",
    "Kyberswap Elastic": "kyberswap-elastic",
    "Lif3 V2": "lif3-v2",
    "Lif3 V3": "lif3-v3",
    "Lighter V2": "lighter-v2",
    "Mad Meerkat Finance": "mad-meerkat-finance",
    "Mad Mex": "mad-mex",
    "MagicFox Stable": "magicfox-stable",
    "MagicFox Volatile": "magicfox-volatile",
    Magician: "magician",
    MeshSwap: "meshswap",
    "Metavault.Trade": "metavault-trade",
    mStable: "mstable",
    "Nacho Finance": "nacho-finance",
    Native: "native",
    NEOPIN: "neopin",
    "Overnight Exchange": "overnight-exchange",
    "Overnight Wrapper": "overnight-wrapper",
    "Pearl Stable": "pearl-stable",
    "Pearl Volatile": "pearl-volatile",
    "Pearl V1.5 Stable": "pearl-v1.5-stable",
    "Pearl V1.5 Volatile": "pearl-v1.5-volatile",
    "Phenix Finance": "phenix-finance",
    Polycat: "polycat",
    Polydex: "polydex",
    PolyWolf: "polywolf",
    Polyzap: "polyzap",
    QuickSwap: "quickswap",
    "QuickSwap V3": "quickswap-v3",
    RadioShack: "radioshack",
    "Retro Finance": "retro-finance",
    SafeSwap: "safeswap",
    "Satin Stable": "satin-stable",
    "Satin Volatile": "satin-volatile",
    SmarDex: "smardex",
    "Smart Dex": "smart-dex",
    SnowSwap: "snowswap",
    SushiSwap: "sushiswap",
    "SushiSwap V3": "sushiswap-v3",
    "Swaap V2": "swaap-v2",
    Synapse: "synapse",
    Twindex: "twindex",
    Unifi: "unifi",
    "Uniswap V2": "uniswap-v2",
    "Uniswap V3": "uniswap-v3",
    VirtuSwap: "virtuswap",
    VulcanDex: "vulcandex",
    WaultSwap: "waultswap",
    "WOOFi V2": "woofi-v2",
    "Wrapped Matic": "wrapped-matic",
    "Wrapped Matic 2": "wrapped-matic-2",
    "Wrapped USDM": "wrapped-usdm",
    "Wrapped USDR": "wrapped-usdr",
  },
  42161: {
    "3xcaliSwap Stable": "3xcaliswap-stable",
    "3xcaliSwap Variable": "3xcaliswap-variable",
    "Aave V3": "aave-v3",
    AlienFi: "alienfi",
    "Angle Savings": "angle-savings",
    ApeSwap: "apeswap",
    "Arbidex Classic": "arbidex-classic",
    "Arbidex Quantum": "arbidex-quantum",
    Arbswap: "arbswap",
    "Arbswap Stable": "arbswap-stable",
    "Auragi Stable": "auragi-stable",
    "Auragi Volatile": "auragi-volatile",
    "Balancer V2 Stable": "balancer-v2-stable",
    "Balancer V2 Weighted": "balancer-v2-weighted",
    "Beefy Finance": "beefy-finance",
    "Button Wrappers": "button-wrappers",
    "Camelot Stable": "camelot-stable",
    "Camelot Volatile": "camelot-volatile",
    "Camelot V3": "camelot-v3",
    "Camelot V3 Legacy": "camelot-v3-legacy",
    "Chronos Stable": "chronos-stable",
    "Chronos Volatile": "chronos-volatile",
    "Chronos V3": "chronos-v3",
    Clober: "clober",
    CrescentSwap: "crescentswap",
    "Curve Crypto Registry": "curve-crypto-registry",
    "Curve Factory": "curve-factory",
    "Curve Registry": "curve-registry",
    "Curve Stable NG": "curve-stable-ng",
    "Curve TriCrypto NG": "curve-tricrypto-ng",
    "Curve TwoCrypto NG": "curve-twocrypto-ng",
    "DackieSwap V2": "dackieswap-v2",
    "DackieSwap V3": "dackieswap-v3",
    DeltaSwap: "deltaswap",
    Dexalot: "dexalot",
    "Dodo V1": "dodo-v1",
    "Dodo V2": "dodo-v2",
    E3: "e3",
    "Elk Finance": "elk-finance",
    "Forge SX Trade": "forge-sx-trade",
    Fraxswap: "fraxswap",
    "Fraxswap V2": "fraxswap-v2",
    GMX: "gmx",
    Hashflow: "hashflow",
    Horiza: "horiza",
    Integral: "integral",
    "Kyber DMM": "kyber-dmm",
    "Kyberswap Elastic": "kyberswap-elastic",
    "Lexer V1": "lexer-v1",
    LFGSwap: "lfgswap",
    Lighter: "lighter",
    "Lighter V2": "lighter-v2",
    "Mad Meerkat Finance": "mad-meerkat-finance",
    "Mad Meerkat Finance V3": "mad-meerkat-finance-v3",
    "MagicFox Stable": "magicfox-stable",
    "MagicFox Volatile": "magicfox-volatile",
    MagicSwap: "magicswap",
    "MIND Games": "mind-games",
    "Mummy Finance": "mummy-finance",
    Mycelium: "mycelium",
    Native: "native",
    OreoSwap: "oreoswap",
    "Overnight Exchange": "overnight-exchange",
    "Overnight Wrapper": "overnight-wrapper",
    PancakeSwap: "pancakeswap",
    "PancakeSwap V3": "pancakeswap-v3",
    "Pancake Stable": "pancake-stable",
    PonySwap: "ponyswap",
    Poolside: "poolside",
    "Radiant V2": "radiant-v2",
    "Ramses Correlated": "ramses-correlated",
    "Ramses Volatile": "ramses-volatile",
    "Ramses V2": "ramses-v2",
    "Rubicon V2": "rubicon-v2",
    "Saddle Finance": "saddle-finance",
    SharkySwap: "sharkyswap",
    ShekelSwap: "shekelswap",
    "Shell V2": "shell-v2",
    "Shell V3": "shell-v3",
    SmarDex: "smardex",
    "SolidLizard Stable": "solidlizard-stable",
    "SolidLizard Volatile": "solidlizard-volatile",
    "Solidly V3": "solidly-v3",
    "Solunea Stable": "solunea-stable",
    "Solunea Volatile": "solunea-volatile",
    SpartaDex: "spartadex",
    "Sterling Stable": "sterling-stable",
    "Sterling Volatile": "sterling-volatile",
    SushiSwap: "sushiswap",
    "SushiSwap V3": "sushiswap-v3",
    "Swaap V2": "swaap-v2",
    SwapFish: "swapfish",
    Swapr: "swapr",
    Swaprum: "swaprum",
    Swapsicle: "swapsicle",
    Synapse: "synapse",
    Tenderizer: "tenderizer",
    TenderSwap: "tenderswap",
    Thick: "thick",
    "Trader Joe": "traderjoe",
    "Trader Joe V2": "traderjoe-v2",
    "Trader Joe V2.1": "traderjoe-v2.1",
    "Uniswap V2": "uniswap-v2",
    "Uniswap V3": "uniswap-v3",
    VirtuSwap: "virtuswap",
    Wombat: "wombat",
    "WOOFi V2": "woofi-v2",
    "Wrapped Ether": "wrapped-ether",
    "Wrapped USDM": "wrapped-usdm",
    "Yearn V2": "yearn-v2",
    ZipSwap: "zipswap",
    ZyberSwap: "zyberswap",
    "ZyberSwap Stable": "zyberswap-stable",
    "ZyberSwap V3": "zyberswap-v3",
  },
  56: {
    Acryptos: "acryptos",
    "Acsi Finance Stable": "acsi-finance-stable",
    "Acsi Finance Weighted": "acsi-finance-weighted",
    AlitaSwap: "alitaswap",
    AliumSwap: "aliumswap",
    "Angle Savings": "angle-savings",
    "Annex Finance": "annex-finance",
    AnnexSwap: "annexswap",
    ApeSwap: "apeswap",
    AutoShark: "autoshark",
    BabyDogeSwap: "babydogeswap",
    BabySwap: "babyswap",
    BakerySwap: "bakeryswap",
    BambooDeFi: "bamboodefi",
    "Baryon Finance": "baryon-finance",
    "Beefy Finance": "beefy-finance",
    BeGlobal: "beglobal",
    BenSwap: "benswap",
    BiSwap: "biswap",
    "BiSwap V3": "biswap-v3",
    BSCswap: "bscswap",
    ButterSwap: "butterswap",
    BXH: "bxh",
    CafeSwap: "cafeswap",
    CheeseSwap: "cheeseswap",
    CoinSwap: "coinswap",
    "Complus Network": "complus-network",
    "Cone Stable": "cone-stable",
    "Cone Volatile": "cone-volatile",
    CorgiSwap: "corgiswap",
    CryptoSwap: "cryptoswap",
    Definix: "definix",
    "Dino.Exchange": "dino-exchange",
    "Dinosaur Eggs": "dinosaur-eggs",
    "Dodo V1": "dodo-v1",
    "Dodo V2": "dodo-v2",
    DOOARSwap: "dooarswap",
    "Dopple Finance": "dopple-finance",
    "Elk Finance": "elk-finance",
    "Ellipsis Crypto": "ellipsis-crypto",
    "Ellipsis Stable": "ellipsis-stable",
    "Empire DEX": "empire-dex",
    FoodCourt: "foodcourt",
    Fraxswap: "fraxswap",
    FstSwap: "fstswap",
    "GIBX Swap": "gibx-swap",
    "Gravis Finance": "gravis-finance",
    "Grizzly Trade": "grizzly-trade",
    Hashflow: "hashflow",
    HyperJump: "hyperjump",
    "Impossible Fi": "impossible-fi",
    iZiSwap: "iziswap",
    JetSwap: "jetswap",
    Jswap: "jswap",
    JulSwap: "jul-swap",
    "Just Money": "just-money",
    "KACO Finance": "kaco-finance",
    KnightSwap: "knightswap",
    KokomoSwap: "kokomoswap",
    KwikSwap: "kwikswap",
    "Kyber DMM": "kyber-dmm",
    "Kyberswap Elastic": "kyberswap-elastic",
    LatteSwap: "latteswap",
    "Lif3 V2": "lif3-v2",
    "Lif3 V3": "lif3-v3",
    "MagicFox Stable": "magicfox-stable",
    "MagicFox Volatile": "magicfox-volatile",
    Maverick: "maverick",
    MDEX: "mdex",
    MochiSwap: "mochiswap",
    MoonLift: "moonlift",
    NarwhalSwap: "narwhalswap",
    Native: "native",
    "Nerve Finance": "nerve-finance",
    NomiSwap: "nomiswap",
    "NomiSwap Stable": "nomiswap-stable",
    "Oni Exchange": "oni-exchange",
    OpenOcean: "openocean",
    OrbitalSwap: "orbitalswap",
    "Orion Protocol": "orion-protocol",
    "Overnight Exchange": "overnight-exchange",
    PadSwap: "padswap",
    "Pancake Stable": "pancake-stable",
    PancakeSwap: "pancakeswap",
    "PancakeSwap V2": "pancakeswap-v2",
    "PancakeSwap V3": "pancakeswap-v3",
    Pandora: "pandora",
    PantherSwap: "pantherswap",
    PinkSwap: "pinkswap",
    "Planet Finance": "planet-finance",
    PureSwap: "pureswap",
    "Radiant V2": "radiant-v2",
    RadioShack: "radioshack",
    "SafeMoon Swap": "safemoon-swap",
    SaitaSwap: "saitaswap",
    Shibance: "shibance",
    "Shibance Inu": "shibance-inu",
    SmarDex: "smardex",
    "SMB Swap": "smb-swap",
    Sphynx: "sphynx",
    SquadSwap: "squadswap",
    "SquadSwap V3": "squadswap-v3",
    StableXSwap: "stablexswap",
    SushiSwap: "sushiswap",
    "SushiSwap V3": "sushiswap-v3",
    SwapFish: "swapfish",
    Swapsicle: "swapsicle",
    SwipeSwap: "swipeswap",
    Swych: "swych",
    Synapse: "synapse",
    TendieSwap: "tendieswap",
    "Thena Fusion": "thena-fusion",
    "Thena Stable": "thena-stable",
    "Thena Volatile": "thena-volatile",
    "Trader Joe": "traderjoe",
    "Trader Joe V2": "traderjoe-v2",
    "Trader Joe V2.1": "traderjoe-v2.1",
    Unifi: "unifi",
    "Uniswap V2": "uniswap-v2",
    "Uniswap V3": "uniswap-v3",
    "USDFI Stable": "usdfi-stable",
    "USDFI Volatile": "usdfi-volatile",
    "Venus Finance": "venus-finance",
    "Veplus Stable": "veplus-stable",
    "Veplus Volatile": "veplus-volatile",
    "W3 Swap": "w3-swap",
    WardenSwap: "wardenswap",
    WaultSwap: "waultswap",
    WinerySwap: "wineryswap",
    Wombat: "wombat",
    "WOOFi V2": "woofi-v2",
    "Wrapped BNB": "wrapped-bnb",
    YieldFields: "yieldfields",
    "Yoshi Exchange": "yoshi-exchange",
    YouSwap: "youswap",
    ZooSwap: "zooswap",
    "0.exchange": "0-exchange",
  },
  8453: {
    "Aave V3": "aave-v3",
    "Aerodrome Slipstream": "aerodrome-slipstream",
    "Aerodrome Stable": "aerodrome-stable",
    "Aerodrome Volatile": "aerodrome-volatile",
    "Alien Base": "alien-base",
    "Alien Base Stable": "alien-base-stable",
    "Alien Base V3": "alien-base-v3",
    "Angle Savings": "angle-savings",
    "Balancer V2 Stable": "balancer-v2-stable",
    "Balancer V2 Weighted": "balancer-v2-weighted",
    Baldex: "baldex",
    BaseSwap: "baseswap",
    BaseSwapX: "baseswapx",
    "Baso Stable": "baso-stable",
    "Baso Volatile": "baso-volatile",
    "Button Wrappers": "button-wrappers",
    CBSwap: "cbswap",
    "Citadel Stable": "citadel-stable",
    "Citadel Volatile": "citadel-volatile",
    CloudBase: "cloudbase",
    "Curve Factory": "curve-factory",
    "Curve Crypto Registry": "curve-crypto-registry",
    "Curve Stable NG": "curve-stable-ng",
    "Curve TriCrypto NG": "curve-tricrypto-ng",
    "Curve TwoCrypto NG": "curve-twocrypto-ng",
    "DackieSwap V2": "dackieswap-v2",
    "DackieSwap V3": "dackieswap-v3",
    E3: "e3",
    "Elk Finance": "elk-finance",
    Graphene: "graphene",
    Horiza: "horiza",
    HorizonDEX: "horizondex",
    "Infusion Stable": "infusion-stable",
    "Infusion Volatile": "infusion-volatile",
    iZiSwap: "iziswap",
    "Kokonut Swap CPMM": "kokonut-swap-cpmm",
    "Kokonut Swap Crypto": "kokonut-swap-crypto",
    "Kyberswap Elastic": "kyberswap-elastic",
    Maverick: "maverick",
    MoonBase: "moonbase",
    Morphex: "morphex",
    "Mummy Finance": "mummy-finance",
    Native: "native",
    "Nether Finance": "nether-finance",
    "Overnight Exchange": "overnight-exchange",
    "Overnight Wrapper": "overnight-wrapper",
    PancakeSwap: "pancakeswap",
    "PancakeSwap V3": "pancakeswap-v3",
    Poolside: "poolside",
    RocketSwap: "rocketswap",
    "Scale Stable": "scale-stable",
    "Scale Volatile": "scale-volatile",
    SharkSwap: "sharkswap",
    SmarDex: "smardex",
    "Solidly V3": "solidly-v3",
    SoSwap: "soswap",
    SushiSwap: "sushiswap",
    "SushiSwap V3": "sushiswap-v3",
    SwapBased: "swapbased",
    "SwapBased CL": "swapbased-cl",
    "SwapBased Perps": "swapbased-perps",
    "SwapBased V3": "swapbased-v3",
    Synapse: "synapse",
    SynthSwap: "synthswap",
    "SynthSwap Perps": "synthswap-perps",
    "SynthSwap V3": "synthswap-v3",
    Thick: "thick",
    "Throne Stable": "throne-stable",
    "Throne V2": "throne-v2",
    "Throne V3": "throne-v3",
    "Uniswap V2": "uniswap-v2",
    "Uniswap V3": "uniswap-v3",
    "Velocimeter Stable": "velocimeter-stable",
    "Velocimeter Volatile": "velocimeter-volatile",
    Voodoo: "voodoo",
    "WOOFi V2": "woofi-v2",
    "Wrapped Ether": "wrapped-ether",
  },
};

export function constructQuery(chainId, includeProtocols, excludeProtocols) {
  const allDEXS = supportedProtocols[chainId];
  let includeDEXS = [];
  let excludeDEXS = [];

  if (includeProtocols) {
    const included = includeProtocols
      .split(",")
      .map((protocol) => protocol.trim());
    includeDEXS = Object.keys(allDEXS).filter((key) =>
      included.includes(allDEXS[key])
    );
    excludeDEXS = Object.keys(allDEXS).filter(
      (key) => !includeDEXS.includes(key)
    );
  } else if (excludeProtocols) {
    const excluded = excludeProtocols
      .split(",")
      .map((protocol) => protocol.trim());
    excludeDEXS = Object.keys(allDEXS).filter((key) =>
      excluded.includes(allDEXS[key])
    );
    includeDEXS = Object.keys(allDEXS).filter(
      (key) => !excludeDEXS.includes(key)
    );
  } else {
    includeDEXS = Object.keys(allDEXS);
  }

  return {
    includeDEXS: includeDEXS.join(","),
    excludeDEXS: excludeDEXS.join(","),
  };
}
