export const supportedProtocols = {
    1: {
        "34": "Uniswap V2",
        "29": "SushiSwap",
        "47": "DeFi Swap",
        "49": "Convergence",
        "48": "LuaSwap",
        "40": "ShibaSwap",
        "30": "PancakeSwap",
        "53": "Uniswap V3",
        "54": "Balancer V1",
        "51": "Balancer V2",
        "55": "Curve V1",
        "259": "Curve",
        "58": "Curve V2",
        "52": "Bancor",
        "59": "Kyber",
        "81": "Synapse",
        "83": "Wombat",
        "80": "DODO",
        "82": "Shell",
        "88": "DODO V2",
        "91": "Smoothy",
        "92": "RadioShack",
        "89": "FraxSwap",
        "99": "OKX DEX",
        "28": "HashFlow",
        "101": "Swapr",
        "104": "Bancor V3",
        "105": "PSM",
        "106": "Balancer",
        "108": "Verse",
        "110": "1inch Limit Order",
        "248": "OKX Limit Order",
        "132": "DefiPlaza",
        "114": "Swerve",
        "113": "Kyber Elastic",
        "131": "StablePlaza",
        "130": "0x Limit Order",
        "133": "Clipper",
        "134": "Lido",
        "135": "Nomiswap Stable",
        "136": "Solidly",
        "215": "Trader Joe V2.1",
        "153": "Cafe Swap",
        "141": "ELK",
        "102": "Unifi",
        "159": "LINKSWAP",
        "160": "Sake Swap",
        "27": "Curve 3CRV",
        "202": "Aave V2",
        "230": "Aave V3",
        "199": "Compound",
        "184": "sfrxETH",
        "186": "stMatic",
        "200": "PancakeSwap V3",
        "203": "RocketPool",
        "207": "Kronos",
        "204": "1inch LP v1.1",
        "210": "Curve TNG",
        "214": "Mooniswap",
        "213": "Integral",
        "218": "Maverick V1",
        "226": "Curve LLAMMA",
        "234": "xSigma",
        "239": "Sushiswap V3",
        "262": "Solidly V3",
    },
    10: {
        "53": "Uniswap V3",
        "51": "Balancer V2",
        "55": "Curve V1",
        "59": "Kyber",
        "83": "Wombat",
        "110": "1inch Limit Order",
        "248": "OKX Limit Order",
        "113": "Kyber Elastic",
        "133": "Clipper",
        "141": "ELK",
        "191": "Trident",
        "181": "Velodrome",
        "249": "Velodrome V2",
        "336": "Velodrome V3",
        "206": "Mummy Finance",
        "230": "Aave V3",
        "219": "hToken",
        "223": "nextToken",
        "257": "Wrapped Synthetix",
        "280": "Clipper Coves",
    },
    137: {
        "29": "SushiSwap",
        "33": "ApeSwap",
        "46": "JetSwap",
        "53": "Uniswap V3",
        "51": "Balancer V2",
        "55": "Curve V1",
        "59": "Kyber",
        "62": "QuickSwap",
        "61": "Dfyn",
        "70": "MM.Finance",
        "81": "Synapse",
        "80": "DODO",
        "88": "DODO V2",
        "92": "RadioShack",
        "90": "Orion",
        "99": "OKX DEX",
        "110": "1inch Limit Order",
        "248": "OKX Limit Order",
        "113": "Kyber Elastic",
        "133": "Clipper",
        "102": "Unifi",
        "157": "Gravity",
        "139": "Polydex",
        "145": "WaultSwap",
        "169": "QuickSwap V3",
        "183": "Dystopia",
        "182": "IronSwap",
        "191": "Trident",
        "179": "MeshSwap",
        "230": "Aave V3",
        "194": "iZUMi",
        "219": "hToken",
        "223": "nextToken",
        "239": "Sushiswap V3",
        "265": "SmarDex",
        "275": "Lif3 Swap",
        "274": "Metavault Trade",
        "270": "Retro",
        "273": "Pearl",
        "272": "Firebird OneSwap",
        "280": "Clipper Coves",
    },
    42161: {
        "29": "SushiSwap",
        "53": "Uniswap V3",
        "51": "Balancer V2",
        "55": "Curve V1",
        "58": "Curve V2",
        "59": "Kyber",
        "60": "Trader Joe",
        "81": "Synapse",
        "83": "Wombat",
        "80": "DODO",
        "88": "DODO V2",
        "93": "LFGSwap",
        "28": "HashFlow",
        "101": "Swapr",
        "110": "1inch Limit Order",
        "248": "OKX Limit Order",
        "113": "Kyber Elastic",
        "133": "Clipper",
        "165": "Camelot",
        "168": "Trader Joe V2",
        "215": "Trader Joe V2.1",
        "144": "Zyber",
        "167": "Zyber Stable",
        "137": "Zyber V3",
        "138": "GMX",
        "141": "ELK",
        "152": "SwapFish",
        "175": "ArbDex",
        "176": "SolidLizard",
        "191": "Trident",
        "230": "Aave V3",
        "198": "Rames Exchange",
        "194": "iZUMi",
        "200": "PancakeSwap V3",
        "330": "CurveNG",
        "211": "Chronos",
        "212": "Arbswap",
        "217": "Camelot V3",
        "213": "Integral",
        "221": "Arbidex V3",
        "222": "ArbSwap Stable",
        "219": "hToken",
        "223": "nextToken",
        "239": "Sushiswap V3",
        "261": "Ramses V2",
        "265": "SmarDex",
    },
    56: {
        "29": "SushiSwap",
        "37": "PancakeSwap V1",
        "39": "MDEX",
        "32": "BiSwap",
        "33": "ApeSwap",
        "35": "BabySwap",
        "36": "KnightSwap",
        "41": "BakerySwap",
        "44": "AutoShark",
        "50": "BenSwap",
        "46": "JetSwap",
        "30": "PancakeSwap",
        "43": "JSwap",
        "53": "Uniswap V3",
        "59": "Kyber",
        "60": "Trader Joe",
        "81": "Synapse",
        "83": "Wombat",
        "80": "DODO",
        "86": "Ellipsis.Finance",
        "88": "DODO V2",
        "91": "Smoothy",
        "92": "RadioShack",
        "90": "Orion",
        "99": "OKX DEX",
        "28": "HashFlow",
        "100": "JulSwap",
        "248": "OKX Limit Order",
        "112": "Nomiswap",
        "113": "Kyber Elastic",
        "135": "Nomiswap Stable",
        "168": "Trader Joe V2",
        "147": "Babydoge",
        "153": "Cafe Swap",
        "150": "Cheese Swap",
        "141": "ELK",
        "146": "HyperJump",
        "149": "PlanetFinance",
        "154": "Swap Swipe",
        "102": "Unifi",
        "148": "Wardenswap",
        "145": "WaultSwap",
        "173": "PancakeSwap Stable",
        "164": "Thena",
        "174": "FstSwap",
        "185": "AnnexFinance",
        "195": "Annex",
        "189": "Cone",
        "180": "Dopple",
        "187": "Acsi Finance",
        "188": "Nerve Finance",
        "191": "Trident",
        "200": "PancakeSwap V3",
        "216": "Thena V2",
        "218": "Maverick V1",
        "223": "nextToken",
        "265": "SmarDex",
        "267": "Spartan V2",
        "275": "Lif3 Swap",
        "271": "Acryptos",
        "269": "USDFI",
    },
    8453: {
        "34": "Uniswap V2",
        "29": "SushiSwap",
        "30": "PancakeSwap",
        "53": "Uniswap V3",
        "51": "Balancer V2",
        "55": "Curve V1",
        "251": "Curve V2 2CRYPTO",
        "81": "Synapse",
        "110": "1inch Limit Order",
        "113": "Kyber Elastic",
        "166": "Equalizer",
        "194": "iZUMi",
        "200": "PancakeSwap V3",
        "210": "Curve TNG",
        "218": "Maverick V1",
        "219": "hToken",
        "227": "BaseSwap",
        "229": "Horizon",
        "235": "Aerodrome",
        "239": "Sushiswap V3",
        "242": "Synthswap V3",
        "241": "DackieSwap",
        "318": "DackieSwap V2",
        "236": "SwapBased V3",
        "238": "SwapBased V2",
        "245": "AlienBase",
        "243": "KokonutSwap",
        "237": "Rocketswap",
        "244": "Synthswap V2",
        "240": "Velocimeter",
        "247": "Baso Finance",
        "246": "BaseSwap V3",
        "262": "Solidly V3",
        "265": "SmarDex",
        "316": "Soswap",
        "334": "Bunny Swap",
    }
};

export function constructQuery(chainId, includeProtocols, excludeProtocols) {
    const allDEXS = supportedProtocols[chainId];
    let includeDEXS = [];
    let excludeDEXS = [];

    if (includeProtocols) {
        const included = includeProtocols
            .split(",")
            .map((protocol) => protocol.trim());
        includeDEXS = Object.keys(allDEXS).filter((key) =>
            included.includes(allDEXS[key])
        );
        excludeDEXS = Object.keys(allDEXS).filter(
            (key) => !includeDEXS.includes(key)
        );
    } else if (excludeProtocols) {
        const excluded = excludeProtocols
            .split(",")
            .map((protocol) => protocol.trim());
        excludeDEXS = Object.keys(allDEXS).filter((key) =>
            excluded.includes(allDEXS[key])
        );
        includeDEXS = Object.keys(allDEXS).filter(
            (key) => !excludeDEXS.includes(key)
        );
    } else {
        includeDEXS = Object.keys(allDEXS);
    }

    return {
        includeDEXS: includeDEXS.join(","),
        excludeDEXS: excludeDEXS.join(","),
    };
}